#ifndef Programms
#define Programms

#include "h/Programm1_1.h"
#include "h/Programm1_2.h"
#include "h/Programm2_1.h"
#include "h/Programm2_2.h"
#include "h/Programm2_3.h"
#include "h/Programm2_4.h"
#include "h/Programm3_1.h"
#include "h/Programm3_2.h"
#include "h/Programm3_3.h"
#include "h/Programm3_4.h"
#include "h/Programm3_5.h"
#include "h/Programm4_1.h"
#include "h/Programm4_2.h"
#include "h/Programm4_3.h"
#include "h/Programm5_1.h"
#include "h/Programm5_2.h"
#include "h/Programm5_3.h"
#include "h/Programm5_4.h"
#include "h/Programm6_1.h"
#include "h/Programm6_2.h"
#include "h/Programm7_1.h"
#include "h/Programm7_2.h"
#include "h/Programm7_3.h"
#include "h/Programm7_4.h"
#include "h/Programm8_1.h"
#include "h/Programm8_2.h"

#endif
